### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by vicMasons** [zingchart/zingtouch#7]
here is the error.

sh-3.2# npm run build:dev

> zingtouch@1.0.0 build:dev /usr/local/lib/node_modules/zingtouch
> webpack

Hash: 64e1cee08a5ee3e5eb87
Version: webpack 1.13.1
Time: 230ms
    + 1 hidden modules

ERROR in ./src/core/main.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/usr/local/lib/node_modules/zingtouch/src/core"
    at /usr/local/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:313:17
    at Array.map (native)
    at OptionManager.resolvePresets (/usr/local/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:305:20)
    at OptionManager.mergePresets (/usr/local/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:288:10)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:14)
    at OptionManager.init (/usr/local/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:360:12)
    at File.initOptions (/usr/local/lib/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/usr/local/lib/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/usr/local/lib/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/usr/local/lib/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/usr/local/lib/node_modules/babel-loader/index.js:88:12)

I would like non mimified

**Comment by mike-schultz** [comment]
You might need to build using an updated node version. Nevertheless, I just included the dependency (babel-preset-es2015) in the package.json directly. Update and give npm install a go one more time. I've thrown up the unminified file in `/dist` as well.
