### ISSUE TITLE
Cannot find module './dist/zingtouch.min.js'

### ISSUE THREAD

**Issue by hashrock** [zingchart/zingtouch#9]
I got the error when I use zingtouch with npm.

Steps to reproduce
------------------

```
$ npm install -S zing-touch
$ node
> var zing = require("zingtouch");
```

Actual behavior
---------------

```
Error: Cannot find module './dist/zingtouch.min.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/hashrock/test/zing-what/node_modules/zingtouch/index.js:1:63)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

`./dist/zingtouch.min.js` is missing but there is `zingtouch-1.0.1.min.js` in node_modules.

```
$ tree
.
└── zingtouch
    ├── LICENSE
    ├── bower.json
    ├── dist
    │   ├── zingtouch-1.0.1.min.js
    │   └── zingtouch.js
    ...

```

Environment data
----------------

 - node v5.11.0
 - npm 3.9.5

**Comment by mike-schultz** [comment]
Thanks for catching that issue! The file was incorrectly published to npm. I bumped the version number to 1.0.2 both in this repo and on npm so it should work now.

Just to note:  incase if you try the new version with the steps above, zingtouch won't work directly in node as it is browser based and it needs the `window` object. You will need to use a tool like browserify to get it to load in the browser if you are using `require` syntax. Feel free to suggest any suggestions if you have any issues with this.

**Comment by hashrock** [comment]
Thank you! 👍 
I'll use zing-touch with webpack.
